######################################################################
# Automatically generated by qmake (3.0) Sun Mar 26 15:22:05 2017
######################################################################

TEMPLATE = app
TARGET = client
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp
