######################################################################
# Automatically generated by qmake (3.0) Sun Mar 26 15:22:05 2017
######################################################################

TEMPLATE = app
TARGET = client
INCLUDEPATH += .

QT += widgets network

RESOURCES = client.qrc

# Input
HEADERS += client.h \
	iohandler.h
SOURCES += main.cpp client.cpp iohandler.cpp
