######################################################################
# Automatically generated by qmake (3.0) Sun Mar 26 15:22:05 2017
######################################################################

TEMPLATE = app
TARGET = client
INCLUDEPATH += .
INCLUDEPATH += $$PWD/../common

QT += widgets network

RESOURCES = client.qrc

# Input
HEADERS += client.h \
	iohandler.h \
	launcher.h \
	../common/protocol.h
SOURCES += main.cpp client.cpp iohandler.cpp launcher.cpp
