######################################################################
# Automatically generated by qmake (3.0) Sun Mar 26 04:50:59 2017
######################################################################

TEMPLATE = app
TARGET = Paper-IO
INCLUDEPATH += .

QT += widgets network

# Input
HEADERS += server/PaperServer.h
SOURCES += server/main.cpp \
	server/PaperServer.cpp 
